"""create initial schema

Revision ID: 87af3ef19695
Revises: 
Create Date: 2026-09-20 18:10:32.346821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87af3ef19695'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('securities_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('securities_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bars_upserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.CheckConstraint("status in ('running', 'succeeded', 'partial', 'failed')", name=op.f('ck_ingestion_runs_status')),
    sa.CheckConstraint("triggered_by in ('schedule', 'manual')", name=op.f('ck_ingestion_runs_triggered_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange_code', sa.String(length=10), nullable=False),
    sa.Column('exchange_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), server_default='equity', nullable=False),
    sa.Column('provider_symbol', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type in ('equity', 'etf')", name=op.f('ck_securities_asset_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_securities')),
    sa.UniqueConstraint('exchange_code', 'symbol', name='uq_securities_exchange_symbol'),
    sa.UniqueConstraint('provider_symbol', name=op.f('uq_securities_provider_symbol'))
    )
    op.create_table('daily_bars',
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_daily_bars_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('security_id', 'trade_date', name=op.f('pk_daily_bars'))
    )
    op.create_table('indicator_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), server_default='1D', nullable=False),
    sa.Column('indicator', sa.String(length=16), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ruleset_version', sa.String(length=16), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("indicator in ('dma', 'rsi', 'ichimoku', 'elliott', 'overall')", name=op.f('ck_indicator_signals_indicator')),
    sa.CheckConstraint("state in ('bullish', 'neutral', 'bearish')", name=op.f('ck_indicator_signals_state')),
    sa.CheckConstraint('score between -2 and 2', name=op.f('ck_indicator_signals_score_range')),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_indicator_signals_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicator_signals')),
    sa.UniqueConstraint('security_id', 'timeframe', 'indicator', 'as_of_date', name='uq_indicator_signals_key')
    )
    op.create_table('signal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), server_default='1D', nullable=False),
    sa.Column('indicator', sa.String(length=16), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('from_state', sa.String(length=8), nullable=False),
    sa.Column('to_state', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("from_state in ('bullish', 'neutral', 'bearish')", name=op.f('ck_signal_events_from_state')),
    sa.CheckConstraint("to_state in ('bullish', 'neutral', 'bearish')", name=op.f('ck_signal_events_to_state')),
    sa.CheckConstraint('from_state <> to_state', name=op.f('ck_signal_events_state_changed')),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_signal_events_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_events')),
    sa.UniqueConstraint('security_id', 'timeframe', 'indicator', 'as_of_date', name='uq_signal_events_key')
    )
    op.create_index(op.f('ix_signal_events_created_at'), 'signal_events', ['created_at'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_watchlist_items_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_items')),
    sa.UniqueConstraint('security_id', name=op.f('uq_watchlist_items_security_id'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_event_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), server_default='telegram', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('pending', 'sent', 'failed')", name=op.f('ck_notifications_status')),
    sa.ForeignKeyConstraint(['signal_event_id'], ['signal_events.id'], name=op.f('fk_notifications_signal_event_id_signal_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('signal_event_id', 'channel', name='uq_notifications_event_channel')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_signal_events_created_at'), table_name='signal_events')
    op.drop_table('signal_events')
    op.drop_table('indicator_signals')
    op.drop_table('daily_bars')
    op.drop_table('securities')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
